config = {
    "target_class": None,
    "batch_size": 32,
    "image_size": 64,
    "num_epochs": 100,
    "latent_space_size": 100,
    "feature_mapG": 64,
    "feature_mapD": 64,
    "lr_g": 0.0022,
    "optimizer_g": "adam",
    "beta1_g": 0.09,
    "beta2_g": 0.999,
    "lr_d": 0.00011,
    "optimizer_d": "adam",
    "beta1_d": 0.8,
    "beta2_d": 0.999,
    "device": "cuda",
    "exp_name": "pretune_unconditional_dcgan",
}